//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lykke.blue.Api.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lykke.blue.Api.Strings.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exists.
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your app version is not supported anymore. Please update your app from Google Play and continue enjoying the service..
        /// </summary>
        internal static string AndroidUpdateNeededMsg {
            get {
                return ResourceManager.GetString("AndroidUpdateNeededMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version not supported. Please, update..
        /// </summary>
        internal static string DefaultUpdateNeededMsg {
            get {
                return ResourceManager.GetString("DefaultUpdateNeededMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field should not be empty.
        /// </summary>
        internal static string FieldShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("FieldShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Format.
        /// </summary>
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not valid.
        /// </summary>
        internal static string InvalidPropertyValue {
            get {
                return ResourceManager.GetString("InvalidPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is {0}.
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is {0}.
        /// </summary>
        internal static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be empty.
        /// </summary>
        internal static string NotEmptyField {
            get {
                return ResourceManager.GetString("NotEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough funds.
        /// </summary>
        internal static string NotEnoughFunds {
            get {
                return ResourceManager.GetString("NotEnoughFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service temporarily unavailable. Sorry for the inconvenience..
        /// </summary>
        internal static string OperationDisabled {
            get {
                return ResourceManager.GetString("OperationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operataion Details Not Found.
        /// </summary>
        internal static string OperationsDetailInfoNotFound {
            get {
                return ResourceManager.GetString("OperationsDetailInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are experiencing technical problems. Please try again..
        /// </summary>
        internal static string TechnicalProblems {
            get {
                return ResourceManager.GetString("TechnicalProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweets Not Found.
        /// </summary>
        internal static string TweetsNotFound {
            get {
                return ResourceManager.GetString("TweetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Not Found.
        /// </summary>
        internal static string UsersByPartnerIdNotFound {
            get {
                return ResourceManager.GetString("UsersByPartnerIdNotFound", resourceCulture);
            }
        }
    }
}
